version: '3'

services:

  webserver:
    image: nginx:alpine
    container_name: cutwise-server
    volumes:
    - ./:/var/www/html
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
    - 80
    restart: always
    environment:
      VIRTUAL_HOST: cutwise.shapkin.org

networks:
  default:
    external:
      name: nginx-proxy